import type { NextPage, GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next'
import Head from 'next/head'
import Script from 'next/script'

import { useMemo } from 'react'

import dynamic from 'next/dynamic'

import axios from 'axios'

const Home: NextPage = (props) => {
  const Map = useMemo(() => dynamic(
    () => import('../components/Home/Home'), // replace '@components/map' with your component's location
    { ssr: false } // This line is important. It's what prevents server-side render
  ),[])

    console.log(props)
    
  return (<>
    <Head>
      <title>Geo Static App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet"
        href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
        integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
      />
    </Head>
    <Script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
      integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
    />
    <Map />
  </>)
}

export const getStaticProps: GetStaticProps = async () => {
  const res = await axios.get(`https://servicodados.ibge.gov.br/api/v1/localidades/estados`);
  const data = await res.data;

  if (!data) {
      return {
          notFound: true,
      }
  }

  return {
      props: { data }, // will be passed to the page component as props
  }
}

export default Home
